if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = '$(TableName)' AND TABLE_SCHEMA = 'dbo') drop table dbo.$(TableName);

CREATE TABLE $(TableName) (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	VOTER_ID varchar(255),
	FIRST_NAME varchar(255),
	MIDDLE_NAME varchar(255),
	LAST_NAME varchar(255),
	NAME_SUFFIX varchar(255),
	VOTER_NAME varchar(255),
	DRIVERS_LICENSE varchar(255),
	SSN varchar(255),
	REGISTRATION_DATE varchar(255),
	EFFECTIVE_DATE varchar(255),
	PHONE_NUM varchar(255),
	HOUSE_NUM varchar(255),
	HOUSE_SUFFIX varchar(255),
	PRE_DIR varchar(255),
	STREET_NAME varchar(255),
	STREET_TYPE varchar(255),
	POST_DIR varchar(255),
	UNIT_TYPE varchar(255),
	UNIT_NUM varchar(255),
	RESIDENTIAL_ADDRESS varchar(255),
	RESIDENTIAL_CITY varchar(255),
	RESIDENTIAL_STATE varchar(255),
	RESIDENTIAL_ZIP_CODE varchar(255),
	RESIDENTIAL_ZIP_PLUS varchar(255),
	MAILING_ADDRESS_1 varchar(255),
	MAILING_ADDRESS_2 varchar(255),
	MAILING_ADDRESS_3 varchar(255),
	MAILING_CITY varchar(255),
	MAILING_STATE varchar(255),
	MAILING_ZIP_CODE varchar(255),
	MAILING_ZIP_PLUS varchar(255),
	MAILING_COUNTRY varchar(255),
	BALLOT_ADDRESS1 varchar(255),
	BALLOT_ADDRESS2 varchar(255),
	BALLOT_ADDRESS3 varchar(255),
	BALLOT_CITY varchar(255),
	BALLOT_STATE varchar(255),
	BALLOT_ZIP_CODE varchar(255),
	BALLOT_ZIP_PLUS varchar(255),
	BALLOT_COUNTRY varchar(255),
	VOTER_STATUS varchar(255),
	STATUS_REASON varchar(255),
	PARTY varchar(255),
	AFF_DATE varchar(255),
	GENDER varchar(255),
	ID_REQUIRED varchar(255),
	BIRTH_YEAR varchar(255),
	PRECINCT_CODE varchar(255),
	PRECINCT_NAME varchar(255),
	UOCAVA varchar(255),
	ISSUE_METHOD varchar(255),
	FAX varchar(255),
	EMAIL varchar(255)
	, CONSTRAINT [PK_$(TableName)] PRIMARY KEY CLUSTERED ([Id] ASC)
)
;